[default]
template_dir = "templates"
script_dir = "template_scripts"
config = "config.json5"

[default.databases.diesel]
url = "db/diesel/db.sqlite"
timeout = 10

[global]
address = "0.0.0.0"
port = 8000