CREATE TABLE qc_forms (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    assemblydate DATETIME NOT NULL,
    buildlocation VARCHAR NOT NULL,
    buildtype VARCHAR NOT NULL,
    drivetype VARCHAR NOT NULL,
    drivesize VARCHAR NOT NULL,
    itemserial VARCHAR NOT NULL,
    asmserial VARCHAR,
    oemserial VARCHAR NOT NULL,
    makemodel VARCHAR NOT NULL,
    msoinstalled BOOLEAN NOT NULL,
    operatingsystem VARCHAR NOT NULL,
    processorgen VARCHAR NOT NULL,
    processortype VARCHAR NOT NULL,
    qc1 VARCHAR NOT NULL,
    qc1initial VARCHAR NOT NULL,
    qc2 VARCHAR NOT NULL,
    qc2initial VARCHAR,

    ramsize VARCHAR NOT NULL,
    ramtype VARCHAR NOT NULL,
    salesorder VARCHAR,
    technotes VARCHAR NOT NULL,
    metadata VARCHAR
);